[package]
name = "daily"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
log = "0.4"
env_logger = "0.8.4"
x11rb = { version = "0.8.1", features = ["randr"] }
