launcher = "/usr/bin/dmenu_run"
terminal = "/usr/bin/xterm"

keybind = [
    { action = "Press",   mod = ["Super", "Shift"], key = 24,  command = "Quit"},
    { action = "Press",   mod = ["Super"],          key = 54,  command = "Close"},
    { action = "Press",   mod = ["Super"],          key = 33,  command = "OpenLauncher"},
    { action = "Press",   mod = ["Super"],          key = 28,  command = "OpenTerminal"},
    { action = "Press",   mod = ["Super"],          key = 23,  command = "FocusNext"},
    { action = "Press",   mod = ["Super", "Shift"], key = 23,  command = "FocusPrev"},
    { action = "Press",   mod = ["Super"],          key = 44,  command = "FocusNextMonitor"},
    { action = "Press",   mod = ["Super"],          key = 45,  command = "FocusPrevMonitor"},
    { action = "Press",   mod = [],                 key = 133, command = "ShowBorder"},
    { action = "Release", mod = ["Super"],          key = 133, command = "HideBorder"},

    { action = "Press",   mod = ["Super"],          key = 10,  command = "Screen1"},
    { action = "Press",   mod = ["Super"],          key = 11,  command = "Screen2"},
    { action = "Press",   mod = ["Super"],          key = 12,  command = "Screen3"},
    { action = "Press",   mod = ["Super"],          key = 13,  command = "Screen4"},
    { action = "Press",   mod = ["Super"],          key = 14,  command = "Screen5"},

    { action = "Press",   mod = ["Super", "Shift"], key = 10,  command = "MoveToScreen1"},
    { action = "Press",   mod = ["Super", "Shift"], key = 11,  command = "MoveToScreen2"},
    { action = "Press",   mod = ["Super", "Shift"], key = 12,  command = "MoveToScreen3"},
    { action = "Press",   mod = ["Super", "Shift"], key = 13,  command = "MoveToScreen4"},
    { action = "Press",   mod = ["Super", "Shift"], key = 14,  command = "MoveToScreen5"},
]

[border]
width = 1
color_focused = "#FF8882"
color_regular = "#505050"
